name: Minedom
version: '${project.version}'
main: com.gertoxq.minedom.Minedom
api-version: 1.19
depend: [ ProtocolLib ]
commands:
  giveitem:
    description: Give yourself custom items
  stats:
    description: Opens a GUI with your stats displayed
  spawn:
    description: Spawns custom entities
  setmana:
    description: Sets your mana
  setstat:
    description: Increases profile stat