name: Minedom
version: '${project.version}'
main: com.gertoxq.minedom.Minedom
api-version: 1.19
commands:
  getstat:
    description: Get the value of a stat of yours
  giveitem:
    description: Get items
  stats:
    description: Opens a GUI with your stats